### ISSUE TITLE
sending packet function bug

### ISSUE THREAD

**Issue by neelkamath** [gkbrk/hackchat#7] opened 2017-05-21 15:58 UTC
I get 
`hackchat.py", line 18, in __init__
    self.send_packet({"cmd": "join", "channel": channel, "nick": nick})
TypeError: send_packet() takes 1 positional argument but 2 were given`
when using the library, both from my own bot as well as from running your example directly.

**Comment by gkbrk** [comment] 2017-05-25 23:42
@neelkamath I cannot reproduce the issue. Can you elaborate on the problem?

**Comment by neelkamath** [comment] 2017-05-26 11:38
When I run your example `hellobot.py`:
```python
#!/usr/bin/python3
import hackchat

chat = hackchat.HackChat("HelloBot", "programming")

def message_got(chat, message, sender):
    if "hello" in message.lower():
        chat.send_message("Hello there {}!".format(sender))

chat.on_message += [message_got]
chat.start_ping_thread() # Send a ping packet every 60 seconds
chat.run_loop()

```
I get this traceback:
```python
C:\Users\neelk\Documents>python test.py
Traceback (most recent call last):
  File "test.py", line 4, in <module>
    chat = hackchat.HackChat("HelloBot", "programming")
  File "C:\Users\neelk\AppData\Local\Programs\Python\Python36-32\lib\site-packages\hackchat.py", line 18, in __init__
    self.send_packet({"cmd": "join", "channel": channel, "nick": nick})
TypeError: send_packet() takes 1 positional argument but 2 were given
```
Maybe you're running with the old `hackchat` module?

**Comment by gkbrk** [comment] 2017-05-26 17:21
It should be fixed, the send_packet signature was missing a self.

**Closed as completed by gkbrk** 2017-05-26 17:21 UTC
